### ISSUE TITLE
Julia 1.0: Compatible XGBoost version?

### ISSUE THREAD

**Issue by ptaitAtMcMaster** [dmlc/XGBoost.jl#54] opened 2018-09-25 16:53 UTC
Hi,
I am trying to add the XGBoost package in a fresh julia 1.0 installation. I am running ubuntu (uname -a output):
Linux 4.4.0-134-generic #160~14.04.1-Ubuntu SMP Fri Aug 17 11:07:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

It appears that there is not a Julia 1.0 compatible version of XGBoost:

(v1.0) pkg> add XGBoost
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package XGBoost [009559a3]:
 XGBoost [009559a3] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0, 0.2.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

Is there a timeline for the package update? Is there anything the community can do to help?
Thanks

**Comment by slundberg** [comment] 2018-09-29 22:07
I was keeping the release cycles up while I was using the XGBoost in Julia extensively, but now I have been swamped with other things so I am not surprised it has issues on 1.0. I am happy to merge any fixes though :)

**Comment by ptaitAtMcMaster** [comment] 2018-10-16 19:06
Hi slundberg - thanks for updating the git repo. Did you get XGBoost working with Julia 1.0?
I tried to install it (see below) in 1.0.1 and it did not work. 

(v1.0) pkg> add XGBoost
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package XGBoost [009559a3]:
 XGBoost [009559a3] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0, 0.2.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by ptaitAtMcMaster** [comment] 2018-10-16 19:21
Hi @slundberg - thanks for updating the git repo. Did you get XGBoost working with Julia 1.0?

Using Julia 1.0.1, building the package directly from the git repo seems to work:
(v1.0) pkg> add https://github.com/dmlc/XGBoost.jl.git
   Cloning git-repo `https://github.com/dmlc/XGBoost.jl.git`
  Updating git-repo `https://github.com/dmlc/XGBoost.jl.git`
 Resolving package versions...
 Installed Compat ──── v1.3.0
 Installed BinDeps ─── v0.8.10
 Installed IterTools ─ v1.1.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [009559a3] + XGBoost v0.2.0+ #master (https://github.com/dmlc/XGBoost.jl.git)
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [9e28174c] + BinDeps v0.8.10
  [34da2185] ↑ Compat v1.1.0 ⇒ v1.3.0
  [c8e1da08] ↑ IterTools v1.0.0 ⇒ v1.1.0
  [009559a3] + XGBoost v0.2.0+ #master (https://github.com/dmlc/XGBoost.jl.git)
  Building XGBoost → `~/.julia/packages/XGBoost/QtQ7P/deps/build.log`

It resulted in one warning:
julia> using XGBoost
[ Info: Precompiling XGBoost [009559a3-9522-5dbb-924b-0b6ed2b22bb9]
┌ Warning: Package XGBoost does not have Libdl in its dependencies:
│ - If you have XGBoost checked out for development and have
│   added Libdl as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with XGBoost
└ Loading Libdl into XGBoost from project dependency, future warnings for XGBoost are suppressed.

I tried to install it from Julia's general registry which did not work:
(v1.0) pkg> add XGBoost
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package XGBoost [009559a3]:
 XGBoost [009559a3] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0, 0.2.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by slundberg** [comment] 2018-10-17 00:39
I just merged a nice PR from @simonschoelly to support 1.0, but PkgDev is failing to install on 1.0 for me right now so I can't tag a new registry version until I figure that out.

**Comment by simonschoelly** [comment] 2018-10-17 01:48
I think PkgDev does not work on Julia v1.0. You probably just have to tag it using github. 
But there is another problem: The tests on travis failed for the macintosh version. https://travis-ci.org/dmlc/XGBoost.jl/jobs/441179595
I think the problem is when build XGBoost, but I can't really fix it, because i don't have a macintosh.

**Comment by microgold** [comment] 2018-10-28 20:06
This worked for me on Julia 1.0.1 but not Julia 1.0.0 (using the PC)

**Comment by ptaitAtMcMaster** [comment] 2018-10-30 00:41
Hi - XGBoost is working for me. 
I am running xgboost on linux
`uname -a
 Linux  4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
I installed it with
`] build https://github.com/dmlc/XGBoost.jl.git`

If you need any more information please let me know.

**Comment by microgold** [comment] 2018-11-11 21:13
I finally got this to work.  There were still a few issues on the PC, but I managed to figure out the problems.  I published an article on using XGBoost and the article explains how I got around these issues.

For example:  I would make it clearer in the instructions, that you need to copy XGBoost.dll into the dep directory.  I would also explain that you need to set the environment variable to master.  Finally, the last line in the deps.jl (the hook)  is never generated, so I had to add it manually.

Other than that, it looks like the compatibility issues for 1.0.1 are working (haven't tried 1.0.2 yet).  Below is my link to the article.  It also provides a good example of using XGBoost in a notebook on the Wilson Breast cancer data:

https://www.linkedin.com/pulse/using-julia-random-forests-xgboost-diagnose-breast-cancer-mike-gold/?published=t

**Comment by slundberg** [comment] 2018-11-20 16:56
@JackDunnNZ I sent a request to get attobot added under dmlc, assuming that works I'll tag a release.

**Comment by JackDunnNZ** [comment] 2018-11-20 17:10
Thanks!

**Comment by oxinabox** [comment] 2019-02-09 16:01
So can a release be tagged?

**Comment by slundberg** [comment] 2019-04-10 16:05
Sorry this took a long time to sort out, but a release is now tagged :)

**Closed by slundberg** 2019-04-10 16:05 UTC

**Comment by oxinabox** [comment] 2019-04-10 18:06
This is really sad, because you tagged a release today, 
and today the release making system is broken.
