### ISSUE TITLE
Package fails to build on Julia 1.0.5

### ISSUE THREAD

**Issue by omus** [dmlc/XGBoost.jl#79] opened 2019-10-03 14:20 UTC
XGBoost v0.4.2 fails to build with Julia 1.0.5 and throws this exception:
```
...
Building XGBoost → `~/.julia/packages/XGBoost/LXjD0/deps/build.log`
┌ Error: Error building `XGBoost`: 
│ [ Info: Downloading https://github.com/JuliaPackaging/Yggdrasil/releases/download/XGBoost-v0.82-2/XGBoost.v0.82.0.x86_64-linux-gnu-cxx11.tar.gz to /root/.julia/packages/XGBoost/LXjD0/deps/usr/downloads/XGBoost.v0.82.0.x86_64-linux-gnu-cxx11.tar.gz...
│ ERROR: LoadError: LibraryProduct(nothing, ["libxgboost", "xgboost"], :libxgboost, "Prefix(/root/.julia/packages/XGBoost/LXjD0/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /root/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:414
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1044
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:392
│  [9] top-level scope at none:0
│ in expression starting at /root/.julia/packages/XGBoost/LXjD0/deps/build.jl:56
[14:19:07] ######################################################################## 100.0% 
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096
```

Steps to reproduce:
```bash
docker run -it --rm amazonlinux
yum install -y curl tar gzip
curl -O https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.5-linux-x86_64.tar.gz
tar xf julia-1.0.5-*
./julia-1.0.5/bin/julia --color=yes -e 'using Pkg; pkg"add XGBoost"'
```

**Comment by omus** [comment] 2019-10-03 14:26
I'll note this issue does not occur when using Julia 1.2

**Comment by aviks** [comment] 2019-10-03 23:34
Ouch, that's unfortunate. I can't replicate on 1.0.4 on windows, and we do have CI enabled for all versions including [1.0.5 on linux](https://travis-ci.org/dmlc/XGBoost.jl/jobs/591246405), so wondering how this slipped past. I'll investigate more.

**Comment by aviks** [comment] 2019-10-03 23:36
@staticfloat any thoughts?

**Comment by staticfloat** [comment] 2019-10-04 00:02
First off, fantastic error report.  It took me all of two minutes to reproduce the problem and find the root cause.

In the short term; do a `yum install libgomp`.  That should solve things instantly.

In the medium term; for Julia 1.0, we should just change the XGBoost tarball to include `libgomp.so` within it.

In the long term; https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/448

**Comment by omus** [comment] 2019-10-05 13:23
Thanks guys!

**Comment by aviks** [comment] 2020-06-29 17:02
XGBoost_jll now has explicit dependency on `CompilerSupportLibraries` and will thus have `libgomp` available (on linux and windows). This is limited to julia 1.3 and above, which is also the support floor for recent versions of the package. Hence, closing.

**Closed by aviks** 2020-06-29 17:02 UTC
